-- Client accounts: logins, sites, change requests, message threads, attachments and an
-- updates feed. Same model as the rest of WBYI: RLS on, no anon policies, every read and
-- write goes through a SECURITY DEFINER function that checks the server key.
-- Attachments live in the database (bytea) rather than Storage, because this project's anon
-- key is public in other sites' bundles and client files can hold personal data.

create table if not exists wbyi_clients (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  name text not null,
  company text,
  plan text not null default 'starter' check (plan in ('starter', 'growth', 'pro', 'priority')),
  billing text not null default 'stripe' check (billing in ('stripe', 'invoice', 'complimentary')),
  anchor_day integer not null default extract(day from now())::int check (anchor_day between 1 and 31),
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);
alter table wbyi_clients enable row level security;

create table if not exists wbyi_client_sites (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references wbyi_clients (id) on delete cascade,
  name text not null,
  url text,
  repo text,
  status text not null default 'live' check (status in ('building', 'live', 'paused')),
  created_at timestamptz not null default now()
);
create index if not exists wbyi_client_sites_client_idx on wbyi_client_sites (client_id);
alter table wbyi_client_sites enable row level security;

create table if not exists wbyi_requests (
  id uuid primary key default gen_random_uuid(),
  ref integer generated by default as identity unique,
  client_id uuid not null references wbyi_clients (id) on delete cascade,
  site_id uuid references wbyi_client_sites (id) on delete set null,
  title text not null,
  details text not null,
  status text not null default 'new' check (status in ('new', 'in_progress', 'needs_info', 'done', 'declined')),
  size text check (size in ('small', 'medium', 'large')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);
create index if not exists wbyi_requests_client_idx on wbyi_requests (client_id, created_at desc);
create index if not exists wbyi_requests_status_idx on wbyi_requests (status);
alter table wbyi_requests enable row level security;

create table if not exists wbyi_request_messages (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references wbyi_requests (id) on delete cascade,
  author text not null check (author in ('client', 'team')),
  body text not null,
  created_at timestamptz not null default now()
);
create index if not exists wbyi_request_messages_req_idx on wbyi_request_messages (request_id, created_at);
alter table wbyi_request_messages enable row level security;

create table if not exists wbyi_attachments (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references wbyi_requests (id) on delete cascade,
  message_id uuid references wbyi_request_messages (id) on delete set null,
  uploaded_by text not null default 'client' check (uploaded_by in ('client', 'team')),
  filename text not null,
  mime text not null,
  bytes integer not null,
  data bytea not null,
  created_at timestamptz not null default now()
);
create index if not exists wbyi_attachments_req_idx on wbyi_attachments (request_id);
alter table wbyi_attachments enable row level security;

create table if not exists wbyi_login_codes (
  id bigint generated always as identity primary key,
  client_id uuid not null references wbyi_clients (id) on delete cascade,
  code_hash text not null,
  token_hash text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  attempts integer not null default 0,
  ip_hash text,
  created_at timestamptz not null default now()
);
create index if not exists wbyi_login_codes_client_idx on wbyi_login_codes (client_id, created_at desc);
create index if not exists wbyi_login_codes_ip_idx on wbyi_login_codes (ip_hash, created_at);
alter table wbyi_login_codes enable row level security;

create table if not exists wbyi_client_updates (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references wbyi_clients (id) on delete cascade,
  site_id uuid references wbyi_client_sites (id) on delete set null,
  request_id uuid references wbyi_requests (id) on delete set null,
  title text not null,
  body text,
  created_at timestamptz not null default now()
);
create index if not exists wbyi_client_updates_client_idx on wbyi_client_updates (client_id, created_at desc);
alter table wbyi_client_updates enable row level security;

-- ---------------------------------------------------------------------------
-- Sign-in: a six-digit code and a link token, both stored hashed, valid 15 minutes.
-- ---------------------------------------------------------------------------

create or replace function wbyi_login_start(p_key text, p_email text, p_code_hash text, p_token_hash text, p_ip_hash text)
returns table (out_client_id uuid, out_name text)
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_id uuid;
  v_name text;
begin
  perform wbyi_check_key(p_key);
  if (select count(*) from wbyi_login_codes l where l.ip_hash = p_ip_hash and l.created_at > now() - interval '24 hours') >= 30 then
    raise exception 'rate_limited';
  end if;
  select c.id, c.name into v_id, v_name from wbyi_clients c where c.email = lower(btrim(p_email));
  if v_id is null then return; end if;
  if (select count(*) from wbyi_login_codes l where l.client_id = v_id and l.created_at > now() - interval '1 hour') >= 6 then
    raise exception 'rate_limited';
  end if;
  insert into wbyi_login_codes (client_id, code_hash, token_hash, expires_at, ip_hash)
  values (v_id, p_code_hash, p_token_hash, now() + interval '15 minutes', p_ip_hash);
  return query select v_id, v_name;
end $$;

-- Checks a code or a link token against the newest unused code for that email.
-- Five wrong codes burn it.
create or replace function wbyi_login_verify(p_key text, p_email text, p_code_hash text, p_token_hash text)
returns uuid
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_client uuid;
  v_row wbyi_login_codes%rowtype;
begin
  perform wbyi_check_key(p_key);
  select c.id into v_client from wbyi_clients c where c.email = lower(btrim(p_email));
  if v_client is null then return null; end if;
  select * into v_row from wbyi_login_codes l
  where l.client_id = v_client and l.used_at is null and l.expires_at > now()
  order by l.created_at desc limit 1
  for update;
  if v_row.id is null then return null; end if;
  if v_row.attempts >= 5 then return null; end if;
  if (p_code_hash is not null and v_row.code_hash = p_code_hash) or (p_token_hash is not null and v_row.token_hash = p_token_hash) then
    update wbyi_login_codes set used_at = now() where id = v_row.id;
    update wbyi_clients set last_login_at = now() where id = v_client;
    return v_client;
  end if;
  update wbyi_login_codes set attempts = attempts + 1 where id = v_row.id;
  return null;
end $$;

-- ---------------------------------------------------------------------------
-- Client reads and writes. p_client_id always comes from the signed session cookie.
-- ---------------------------------------------------------------------------

create or replace function wbyi_client_home(p_key text, p_client_id uuid, p_since timestamptz)
returns json
language plpgsql security definer set search_path = public, extensions as $$
declare v json;
begin
  perform wbyi_check_key(p_key);
  select json_build_object(
    'client', (select json_build_object('id', c.id, 'email', c.email, 'name', c.name, 'company', c.company, 'plan', c.plan, 'anchor_day', c.anchor_day, 'created_at', c.created_at)
               from wbyi_clients c where c.id = p_client_id),
    'sites', coalesce((select json_agg(json_build_object('id', s.id, 'name', s.name, 'url', s.url, 'status', s.status) order by s.created_at)
               from wbyi_client_sites s where s.client_id = p_client_id), '[]'::json),
    'requests', coalesce((select json_agg(r order by r.updated_at desc) from (
               select q.id, q.ref, q.title, q.status, q.size, q.site_id, q.created_at, q.updated_at, q.completed_at,
                      (select count(*) from wbyi_request_messages m where m.request_id = q.id) as messages,
                      (select m.author from wbyi_request_messages m where m.request_id = q.id order by m.created_at desc limit 1) as last_author
               from wbyi_requests q where q.client_id = p_client_id order by q.updated_at desc limit 100) r), '[]'::json),
    'updates', coalesce((select json_agg(u order by u.created_at desc) from (
               select x.id, x.title, x.body, x.request_id, x.created_at from wbyi_client_updates x
               where x.client_id = p_client_id order by x.created_at desc limit 30) u), '[]'::json),
    'used_units', (select coalesce(sum(case q.size when 'small' then 1 when 'medium' then 3 when 'large' then 8 else 0 end), 0)
               from wbyi_requests q where q.client_id = p_client_id and q.status = 'done' and q.completed_at >= p_since)
  ) into v;
  return v;
end $$;

-- p_client_id null = the team (admin or agent) reading any request.
create or replace function wbyi_request_get(p_key text, p_client_id uuid, p_request_id uuid)
returns json
language plpgsql security definer set search_path = public, extensions as $$
declare v json;
begin
  perform wbyi_check_key(p_key);
  if not exists (select 1 from wbyi_requests q where q.id = p_request_id and (p_client_id is null or q.client_id = p_client_id)) then
    return null;
  end if;
  select json_build_object(
    'request', (select json_build_object('id', q.id, 'ref', q.ref, 'title', q.title, 'details', q.details, 'status', q.status, 'size', q.size,
                  'created_at', q.created_at, 'updated_at', q.updated_at, 'completed_at', q.completed_at, 'site_id', q.site_id,
                  'site', (select json_build_object('name', s.name, 'url', s.url, 'repo', s.repo) from wbyi_client_sites s where s.id = q.site_id),
                  'client', (select json_build_object('id', c.id, 'name', c.name, 'email', c.email, 'plan', c.plan) from wbyi_clients c where c.id = q.client_id))
                from wbyi_requests q where q.id = p_request_id),
    'messages', coalesce((select json_agg(json_build_object('id', m.id, 'author', m.author, 'body', m.body, 'created_at', m.created_at) order by m.created_at)
                from wbyi_request_messages m where m.request_id = p_request_id), '[]'::json),
    'attachments', coalesce((select json_agg(json_build_object('id', a.id, 'message_id', a.message_id, 'uploaded_by', a.uploaded_by, 'filename', a.filename,
                  'mime', a.mime, 'bytes', a.bytes, 'created_at', a.created_at) order by a.created_at)
                from wbyi_attachments a where a.request_id = p_request_id), '[]'::json)
  ) into v;
  return v;
end $$;

create or replace function wbyi_request_create(p_key text, p_client_id uuid, p_site_id uuid, p_title text, p_details text)
returns table (out_id uuid, out_ref integer)
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_id uuid;
  v_ref integer;
begin
  perform wbyi_check_key(p_key);
  if char_length(btrim(coalesce(p_title, ''))) < 3 then raise exception 'title_length'; end if;
  if p_site_id is not null and not exists (select 1 from wbyi_client_sites s where s.id = p_site_id and s.client_id = p_client_id) then
    raise exception 'site_not_found';
  end if;
  if (select count(*) from wbyi_requests q where q.client_id = p_client_id and q.created_at > now() - interval '24 hours') >= 40 then
    raise exception 'rate_limited';
  end if;
  insert into wbyi_requests (client_id, site_id, title, details)
  values (p_client_id, p_site_id, left(btrim(p_title), 120), left(btrim(coalesce(p_details, '')), 8000))
  returning id, ref into v_id, v_ref;
  return query select v_id, v_ref;
end $$;

-- p_client_id null = a reply from the team.
create or replace function wbyi_request_reply(p_key text, p_client_id uuid, p_request_id uuid, p_body text)
returns uuid
language plpgsql security definer set search_path = public, extensions as $$
declare v_id uuid;
begin
  perform wbyi_check_key(p_key);
  if not exists (select 1 from wbyi_requests q where q.id = p_request_id and (p_client_id is null or q.client_id = p_client_id)) then
    raise exception 'not_found';
  end if;
  if char_length(btrim(coalesce(p_body, ''))) < 1 then raise exception 'message_length'; end if;
  insert into wbyi_request_messages (request_id, author, body)
  values (p_request_id, case when p_client_id is null then 'team' else 'client' end, left(btrim(p_body), 8000))
  returning id into v_id;
  update wbyi_requests set updated_at = now(),
    status = case when p_client_id is not null and status = 'needs_info' then 'in_progress'
                  when p_client_id is not null and status in ('done', 'declined') then 'new'
                  else status end,
    completed_at = case when p_client_id is not null and status in ('done', 'declined') then null else completed_at end
  where id = p_request_id;
  return v_id;
end $$;

create or replace function wbyi_attachment_add(
  p_key text, p_client_id uuid, p_request_id uuid, p_message_id uuid, p_filename text, p_mime text, p_data text
) returns uuid
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_bytes bytea := decode(p_data, 'base64');
  v_id uuid;
begin
  perform wbyi_check_key(p_key);
  if not exists (select 1 from wbyi_requests q where q.id = p_request_id and (p_client_id is null or q.client_id = p_client_id)) then
    raise exception 'not_found';
  end if;
  if octet_length(v_bytes) > 4500000 then raise exception 'file_too_large'; end if;
  if (select count(*) from wbyi_attachments a where a.request_id = p_request_id) >= 30 then raise exception 'too_many_files'; end if;
  insert into wbyi_attachments (request_id, message_id, uploaded_by, filename, mime, bytes, data)
  values (p_request_id, p_message_id, case when p_client_id is null then 'team' else 'client' end,
          left(p_filename, 160), left(p_mime, 100), octet_length(v_bytes), v_bytes)
  returning id into v_id;
  return v_id;
end $$;

create or replace function wbyi_attachment_get(p_key text, p_client_id uuid, p_attachment_id uuid)
returns table (out_filename text, out_mime text, out_data text)
language plpgsql security definer set search_path = public, extensions as $$
begin
  perform wbyi_check_key(p_key);
  return query
  select a.filename, a.mime, encode(a.data, 'base64')
  from wbyi_attachments a join wbyi_requests q on q.id = a.request_id
  where a.id = p_attachment_id and (p_client_id is null or q.client_id = p_client_id);
end $$;

-- ---------------------------------------------------------------------------
-- Team side: admin screen and the agent API.
-- ---------------------------------------------------------------------------

create or replace function wbyi_admin_client_upsert(p_key text, p_email text, p_name text, p_company text, p_plan text, p_billing text)
returns uuid
language plpgsql security definer set search_path = public, extensions as $$
declare v_id uuid;
begin
  perform wbyi_check_key(p_key);
  insert into wbyi_clients (email, name, company, plan, billing)
  values (lower(btrim(p_email)), btrim(p_name), nullif(btrim(coalesce(p_company, '')), ''), coalesce(p_plan, 'starter'), coalesce(p_billing, 'stripe'))
  on conflict (email) do update set name = excluded.name, company = excluded.company, plan = excluded.plan, billing = excluded.billing
  returning id into v_id;
  return v_id;
end $$;

create or replace function wbyi_admin_client_set_email(p_key text, p_client_id uuid, p_email text)
returns void
language plpgsql security definer set search_path = public, extensions as $$
begin
  perform wbyi_check_key(p_key);
  update wbyi_clients set email = lower(btrim(p_email)) where id = p_client_id;
end $$;

create or replace function wbyi_admin_site_add(p_key text, p_client_id uuid, p_name text, p_url text, p_repo text, p_status text)
returns uuid
language plpgsql security definer set search_path = public, extensions as $$
declare v_id uuid;
begin
  perform wbyi_check_key(p_key);
  insert into wbyi_client_sites (client_id, name, url, repo, status)
  values (p_client_id, btrim(p_name), nullif(btrim(coalesce(p_url, '')), ''), nullif(btrim(coalesce(p_repo, '')), ''), coalesce(p_status, 'live'))
  returning id into v_id;
  return v_id;
end $$;

create or replace function wbyi_admin_clients(p_key text)
returns json
language plpgsql security definer set search_path = public, extensions as $$
declare v json;
begin
  perform wbyi_check_key(p_key);
  select coalesce(json_agg(x order by x.created_at), '[]'::json) into v from (
    select c.id, c.email, c.name, c.company, c.plan, c.billing, c.anchor_day, c.created_at, c.last_login_at,
      coalesce((select json_agg(json_build_object('id', s.id, 'name', s.name, 'url', s.url, 'repo', s.repo, 'status', s.status))
                from wbyi_client_sites s where s.client_id = c.id), '[]'::json) as sites,
      (select count(*) from wbyi_requests q where q.client_id = c.id and q.status in ('new', 'in_progress', 'needs_info')) as open_requests
    from wbyi_clients c
  ) x;
  return v;
end $$;

-- Requests for the team queue, newest activity first, with the latest message.
create or replace function wbyi_admin_requests(p_key text, p_statuses text[])
returns json
language plpgsql security definer set search_path = public, extensions as $$
declare v json;
begin
  perform wbyi_check_key(p_key);
  select coalesce(json_agg(x order by x.priority_rank, x.updated_at desc), '[]'::json) into v from (
    select q.id, q.ref, q.title, q.details, q.status, q.size, q.created_at, q.updated_at, q.completed_at,
      c.id as client_id, c.name as client_name, c.email as client_email, c.plan,
      case c.plan when 'priority' then 0 when 'pro' then 1 when 'growth' then 2 else 3 end as priority_rank,
      s.name as site_name, s.url as site_url, s.repo as site_repo,
      (select count(*) from wbyi_attachments a where a.request_id = q.id) as attachments,
      (select json_build_object('author', m.author, 'body', left(m.body, 400), 'created_at', m.created_at)
         from wbyi_request_messages m where m.request_id = q.id order by m.created_at desc limit 1) as last_message
    from wbyi_requests q
    join wbyi_clients c on c.id = q.client_id
    left join wbyi_client_sites s on s.id = q.site_id
    where p_statuses is null or q.status = any (p_statuses)
    limit 300
  ) x;
  return v;
end $$;

create or replace function wbyi_admin_request_update(p_key text, p_request_id uuid, p_status text, p_size text)
returns void
language plpgsql security definer set search_path = public, extensions as $$
begin
  perform wbyi_check_key(p_key);
  if p_status is not null and p_status not in ('new', 'in_progress', 'needs_info', 'done', 'declined') then raise exception 'bad_status'; end if;
  if p_size is not null and p_size not in ('small', 'medium', 'large') then raise exception 'bad_size'; end if;
  update wbyi_requests
  set status = coalesce(p_status, status),
      size = coalesce(p_size, size),
      updated_at = now(),
      completed_at = case when p_status = 'done' then coalesce(completed_at, now())
                          when p_status is not null and p_status <> 'done' then null
                          else completed_at end
  where id = p_request_id;
end $$;

create or replace function wbyi_admin_update_post(p_key text, p_client_id uuid, p_site_id uuid, p_request_id uuid, p_title text, p_body text, p_at timestamptz)
returns uuid
language plpgsql security definer set search_path = public, extensions as $$
declare v_id uuid;
begin
  perform wbyi_check_key(p_key);
  insert into wbyi_client_updates (client_id, site_id, request_id, title, body, created_at)
  values (p_client_id, p_site_id, p_request_id, left(btrim(p_title), 200), nullif(btrim(coalesce(p_body, '')), ''), coalesce(p_at, now()))
  returning id into v_id;
  return v_id;
end $$;
